name: Trigger Despatch and Deploy

on:
  schedule:
    - cron: "*/5 10-15 * * 1-5"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to dispatch other workflows

    steps:
      - name: Trigger "Despatch"
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/171883506/dispatches \
            -d '{"ref":"main"}'

      - name: Trigger "Deploy Hugo site to Pages"
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/169602592/dispatches \
            -d '{"ref":"main"}'
